name: Deploy Gatsby to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'  # content 폴더 내 변경 사항이 있을 때만 실행
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: 최신 LTS Node.js 설정 (Node 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 의존성 설치
        run: npm install --legacy-peer-deps

      - name: Gatsby 빌드
        run: npm run build -- --prefix-paths

      - name: GitHub Pages 배포
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

          # GitHub Actions에서 원격 저장소 URL을 명확하게 설정
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export GITHUB_REPOSITORY=${{ github.repository }}

          npm run deploy-in-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
